<a href="https://colab.research.google.com/github/krishna4003/Next-Word-Prediction-Project/blob/main/Next_Word_Prediction_Project_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
import numpy as np

In [ ]:
faqs = """About the Program
What is the course fee for Data Science Mentorship Program
The course follows a monthly subscription model where you have to make monthly payments of RS 800
what is the total duration of the course?
what is the syllabus of mentorship program?
we will be covering the following modules:
Python fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning will not be a part of this program's curriculum
What if I miss a live session? Will I get a recording of the session?
Yes, all our sessions are recorded, so even if you miss a session you can go back and watch the recording
What is the time duration of all the sessions?
Roughly, all the sessions last 2 hours?"""



In [ ]:
#Initialize the tokenizer and fit on the text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([faqs])

In [ ]:
#Retrieving the Word Index:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'a': 3,
 'what': 4,
 'program': 5,
 'is': 6,
 'for': 7,
 'data': 8,
 'will': 9,
 'course': 10,
 'science': 11,
 'you': 12,
 'be': 13,
 'learning': 14,
 'and': 15,
 'session': 16,
 'all': 17,
 'sessions': 18,
 'mentorship': 19,
 'monthly': 20,
 'duration': 21,
 'python': 22,
 'ml': 23,
 'deep': 24,
 'nlp': 25,
 'part': 26,
 'this': 27,
 'if': 28,
 'i': 29,
 'miss': 30,
 'recording': 31,
 'about': 32,
 'fee': 33,
 'follows': 34,
 'subscription': 35,
 'model': 36,
 'where': 37,
 'have': 38,
 'to': 39,
 'make': 40,
 'payments': 41,
 'rs': 42,
 '800': 43,
 'total': 44,
 'syllabus': 45,
 'we': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 'fundamentals': 50,
 'libraries': 51,
 'analysis': 52,
 'sql': 53,
 'maths': 54,
 'machine': 55,
 'algorithms': 56,
 'practical': 57,
 'mlops': 58,
 'case': 59,
 'studies': 60,
 'no': 61,
 'not': 62,
 "program's": 63,
 'curriculum': 64,
 'live': 65,
 'get': 66,
 'yes': 67,
 'our': 68,
 'are': 69,
 'recorded': 70,
 'so': 71,
 

In [ ]:
for sentence in faqs.split('\n'): # Breakdown the faqs dataset into sentence by sentence on the basis of line change
  print(tokenizer.texts_to_sequences([sentence])[0]) # 2D list->1D list using [0]


[32, 1, 5]
[4, 6, 1, 10, 33, 7, 8, 11, 19, 5]
[1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20, 41, 2, 42, 43]
[4, 6, 1, 44, 21, 2, 1, 10]
[4, 6, 1, 45, 2, 19, 5]
[46, 9, 13, 47, 1, 48, 49]
[22, 50]
[22, 51, 7, 8, 11]
[8, 52]
[53, 7, 8, 11]
[54, 7, 55, 14]
[23, 56]
[57, 23]
[58]
[59, 60]
[9, 24, 14, 15, 25, 13, 3, 26, 2, 27, 5]
[61, 25, 15, 24, 14, 9, 62, 13, 3, 26, 2, 27, 63, 64]
[4, 28, 29, 30, 3, 65, 16, 9, 29, 66, 3, 31, 2, 1, 16]
[67, 17, 68, 18, 69, 70, 71, 72, 28, 12, 30, 3, 16, 12, 73, 74, 75, 15, 76, 1, 31]
[4, 6, 1, 77, 21, 2, 17, 1, 18]
[78, 17, 1, 18, 79, 80, 81]


In [ ]:
# Get the vocabulary size
vocab_size = len(tokenizer.word_index) + 1  #Including the reserved 0 index
print(f'Vocabulary Size: {vocab_size}')

Vocabulary Size: 82


In [ ]:
 input_sequences=[]
 for sentence in faqs.split('\n'):

  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]


  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences#(2-d list)

[[32, 1],
 [32, 1, 5],
 [4, 6],
 [4, 6, 1],
 [4, 6, 1, 10],
 [4, 6, 1, 10, 33],
 [4, 6, 1, 10, 33, 7],
 [4, 6, 1, 10, 33, 7, 8],
 [4, 6, 1, 10, 33, 7, 8, 11],
 [4, 6, 1, 10, 33, 7, 8, 11, 19],
 [4, 6, 1, 10, 33, 7, 8, 11, 19, 5],
 [1, 10],
 [1, 10, 34],
 [1, 10, 34, 3],
 [1, 10, 34, 3, 20],
 [1, 10, 34, 3, 20, 35],
 [1, 10, 34, 3, 20, 35, 36],
 [1, 10, 34, 3, 20, 35, 36, 37],
 [1, 10, 34, 3, 20, 35, 36, 37, 12],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20, 41],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20, 41, 2],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20, 41, 2, 42],
 [1, 10, 34, 3, 20, 35, 36, 37, 12, 38, 39, 40, 20, 41, 2, 42, 43],
 [4, 6],
 [4, 6, 1],
 [4, 6, 1, 44],
 [4, 6, 1, 44, 21],
 [4, 6, 1, 44, 21, 2],
 [4, 6, 1, 44, 21, 2, 1],
 [4, 6, 1, 44, 21, 2, 1, 10],
 [4, 6],
 [

In [ ]:

[len(x) for x in input_sequences]



[2,
 3,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 2,
 3,
 4,
 5,
 6,
 7,
 2,
 3,
 4,
 5,
 6,
 7,
 2,
 2,
 3,
 4,
 5,
 2,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 2,
 2,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 2,
 3,
 4,
 5,
 6,
 7]

In [ ]:
max_len=max([len(x) for x in input_sequences])
print(max_len)

21


In [ ]:
# Pad the sequences to the same length
padded_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
print(padded_sequences)

[[ 0  0  0 ...  0 32  1]
 [ 0  0  0 ... 32  1  5]
 [ 0  0  0 ...  0  4  6]
 ...
 [ 0  0  0 ...  1 18 79]
 [ 0  0  0 ... 18 79 80]
 [ 0  0  0 ... 79 80 81]]


In [ ]:
# Define the input (X) and output (y)
X = padded_sequences[:, :-1] # all rows and exclude last column
y = padded_sequences[:, -1]  # all rows and include last column

In [ ]:
X.shape

(132, 20)

In [ ]:
y.shape

(132,)

In [ ]:
print(X)

[[ 0  0  0 ...  0  0 32]
 [ 0  0  0 ...  0 32  1]
 [ 0  0  0 ...  0  0  4]
 ...
 [ 0  0  0 ... 17  1 18]
 [ 0  0  0 ...  1 18 79]
 [ 0  0  0 ... 18 79 80]]


In [ ]:
print(y)

[ 1  5  6  1 10 33  7  8 11 19  5 10 34  3 20 35 36 37 12 38 39 40 20 41
  2 42 43  6  1 44 21  2  1 10  6  1 45  2 19  5  9 13 47  1 48 49 50 51
  7  8 11 52  7  8 11  7 55 14 56 23 60 24 14 15 25 13  3 26  2 27  5 25
 15 24 14  9 62 13  3 26  2 27 63 64 28 29 30  3 65 16  9 29 66  3 31  2
  1 16 17 68 18 69 70 71 72 28 12 30  3 16 12 73 74 75 15 76  1 31  6  1
 77 21  2 17  1 18 17  1 18 79 80 81]


In [ ]:
len(tokenizer.word_index)

81

In [ ]:
# Convert the output to categorical
y = to_categorical(y, num_classes=82)# Here no of classes=len(tokenizer.word_index)+1=81+1=82

In [ ]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
y[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
print(f'Input shape: {X.shape}')
print(f'Output shape: {y.shape}')

Input shape: (132, 20)
Output shape: (132, 82)


In [ ]:
input_length = X.shape[1]

In [ ]:
print(input_length)

20


In [ ]:
from tensorflow.keras.layers import  Bidirectional,Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
model = models.Sequential()
model.add(Embedding(82,100,input_length=20))
model.add(LSTM(64))
model.add(LSTM(32))
model.add(Dense(82,activation='softmax'))











In [ ]:

model = models.Sequential()
model.add(Embedding(82,100,input_length=20))
model.add(LSTM(150,return_sequences=True))
model.add(LSTM(100,return_sequences=True))
model.add(LSTM(50))



model.add(Dense(82,activation='softmax'))

In [ ]:
model = models.Sequential()
model.add(Embedding(82,100,input_length=20))
model.add(Bidirectional(LSTM(64, return_sequences=True)))
model.add(Bidirectional(LSTM(32)))
model.add(Dense(82,activation='softmax'))



In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

In [ ]:
text="The course follows"
for i in range(10):
  token_text=tokenizer.texts_to_sequences([text])[0]
  padden_token_text=pad_sequences([token_text],maxlen=20,padding='pre')
  pos=np.argmax(model.predict(padden_token_text))

  for word,index in tokenizer.word_index.items():

    if index==pos:
      text=text + " " + word
      print(text)

1/1 [==============================] - 0s 26ms/step
The course follows a
1/1 [==============================] - 0s 26ms/step
The course follows a monthly
1/1 [==============================] - 0s 25ms/step
The course follows a monthly subscription
1/1 [==============================] - 0s 26ms/step
The course follows a monthly subscription model
1/1 [==============================] - 0s 25ms/step
The course follows a monthly subscription model where
1/1 [==============================] - 0s 28ms/step
The course follows a monthly subscription model where you
1/1 [==============================] - 0s 27ms/step
The course follows a monthly subscription model where you have
1/1 [==============================] - 0s 31ms/step
The course follows a monthly subscription model where you have to
1/1 [==============================] - 0s 26ms/step
The course follows a monthly subscription model where you have to make
1/1 [==============================] - 0s 26ms/step
The course follows a monthly